
#Explosions Config. Synced from server to client.
[explosions]
	#Whether bombs not loaded in the world can be detonated
	detonateUnloadedBombs = false

	#Bomb explosion settings
	[explosions.bombs]
		#Strength value of the Little Boy
		#Range: 0 ~ 1000
		littleBoyStrength = 240
		#Strength value of the Fat Man
		#Range: 0 ~ 1000
		fatManStrength = 350
		#Strength value of nuclear missiles
		#Range: 0 ~ 1000
		missileStrength = 200

	#Explosion behaviour settings
	[explosions.behaviour]
		#The maximum amount of blocks destroyed by an explosion per tick
		#Range: 1 ~ 1000000000
		explosionSpeed = 3072
		#Modifies the range of the fallout area (value in percent)
		#Range: 0.0 ~ 100000.0
		falloutRange = 100.0
		#The amount of block columns changed per tick by fallout after explosions
		#Range: 1 ~ 1000000000
		falloutSpeed = 256
		#Splits the nuclear explosion algorithm into multiple phases, sending blocks and updating lighting afterwards. Goes easier on TPS, FPS and client connection. Disabling this will get the old "animation" back.
		phasedExplosion = true

