
#Radiation Config. Synced from server to client.
[radiation]
	#Whether entities can get irradiated
	enableEntityIrradiation = true
	#RAD/s in the nether (or other warm dimensions, if applicable)
	#Range: 0.0 ~ 1000.0
	netherRadiation = 0.1
	#Whether high radiation levels should perform changes to the world
	worldRadiationEffects = true
	#The least amount of RADs required in a chunk for block modifications to happen
	#Range: 0.5 ~ 1000000.0
	worldRadiationThreshold = 20.0

