
#Settings for Turbine
[turbine]
	#Multiblock min size.
	#Range: 5 ~ 25
	min_size = 5
	#Multiblock max size.
	#Range: 5 ~ 25
	max_size = 24
	#Steam flow per blade mB/t
	#Range: 100 ~ 1000000
	blade_flow = 2000
	#Efficiency %: gold, aluminium, copper, magnesium, beryllium, silver
	efficiency = [104.0, 98.0, 110.0, 86.0, 90.0, 112.0]
	#Default placement rules have all examples
	placement_explanations = ""
	gold = ["turbine_beryllium_coil"]
	aluminium = ["turbine_gold_coil|turbine_magnesium_coil|turbine_beryllium_coil|turbine_gold_coil|turbine_copper_coil"]
	copper = ["turbine_gold_coil"]
	magnesium = ["turbine_bearing"]
	beryllium = ["turbine_magnesium_coil"]
	silver = ["turbine_magnesium_coil", "turbine_gold_coil"]

