
#Client config. Only present on client, duh.
[client]
	#Will show a chat message with update info if a newer version of NTM is available
	displayUpdateMessage = true

	#Render settings
	[client.rendering]
		#Disable this if there are any rendering problems with other mods. Please leave it on otherwise for *respect*.
		displayCustomCapes = true

	#Particle settings
	[client.particles]
		#How many meteor trail particle emitters are spawned per tick. One emitter renders ten particles.
		#Range: 0 ~ 20
		meteorTrailsPerTick = 6

