
#RBMK config. Changes should reload automatically.
[rbmk]
	#The percentage step size how quickly neighboring component heat equalizes, 1 is instant, 0.5 is in 50% steps, etc.
	#Range: 0.0 ~ 1.0
	passiveCooling = 0.2
	#Modifies the fuel rod diffusion, i.e. how quickly the core and hull temperatures equalize
	#Range: 0.0 ~ Infinity
	fuelDiffusionMod = 1.0
	#The percentage step size how quickly the fuel hull heat and the component heat equalize
	#Range: 0.0 ~ 1.0
	heatProvision = 0.2
	#The columns' placement height, doesn't affect previously placed columns
	#Range: 1 ~ 15
	columnHeight = 4
	#Toggles whether scrap entities despawn on their own or remain alive until picked up
	permanentScrap = true
	#How many heat units are consumed per mB water in steam channels
	#Range: 0.0 ~ Infinity
	boilerHeatConsumption = 0.1
	#Modifies how quickly the control rods move
	#Range: 0.0 ~ Infinity
	controlSpeedMod = 1.0
	#Modifies how much flux the rods give out
	#Range: 0.0 ~ Infinity
	reactivityMod = 1.0
	#Modifies how quickly outgasser recipes progress
	#Range: 0.0 ~ Infinity
	outgasserMod = 1.0
	#Modifies the power surge when inserting control rods
	#Range: 0.0 ~ Infinity
	surgeMod = 1.0
	#How far the flux of a normal fuel rod reaches
	#Range: 1 ~ 100
	fluxRange = 5
	#Toggles whether fuel columns should initiate a meltdown when overheating
	disableMeltdowns = false

	#ReaSim specific settings
	[rbmk.reasim]
		#How far the flux of a ReaSim fuel rod reaches
		#Range: 1 ~ 100
		reasimRange = 10
		#How many neutrons are created from ReaSim fuel rods
		#Range: 1 ~ 24
		reasimCount = 6
		#Modifies the outgoing flux of individual streams from the ReaSim fuel rod to compensate for the potentially increased stream count
		#Range: 0.0 ~ Infinity
		reasimMod = 1.0
		#Whether all components should act like boilers with dedicated in/outlet columns (true when 528 specific option is set)
		reasimBoilers = false
		#The percentage of possible steam ending up being produced per tick
		#Range: 0.0 ~ 1.0
		reasimBoilerSpeed = 0.05

